name: Node.js CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]  # Specify Node.js version here

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4

      # Use the specified Node.js version and enable npm caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies using npm ci (Clean Install)
      - name: Install dependencies
        run: |
          cd StableBillingBackend
          npm ci

      # Build the project (if a build script exists)
      - name: Build the project
        run: |
          cd StableBillingBackend
          npm run build --if-present

      # Restart the backend service with pm2 (Update environment variables if needed)
      - name: Restart backend service with pm2
        run: |
          cd StableBillingBackend
          pm2 restart src/index.js --update-env
