name: Node.js CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'StableBillingBackend/package-lock.json'  # Add this line

      - name: Install dependencies
        run: |
          cd StableBillingBackend
          npm ci

      - name: Build the project
        run: |
          cd StableBillingBackend
          npm run build --if-present

      - name: Restart backend service with pm2
        run: |
          cd StableBillingBackend
          pm2 restart src/index.js --update-env